name: Build and Release apk
on: 
  push:
    tags:
      - '*'

jobs:

  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'
    - run: cd ./dev/neat/ && flutter pub get
    - run: cd ./dev/neat/ && flutter build apk --release
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/flutter-apk/*.apk"
        token: ${{ secrets.NEAT_TOKEN }}