name: Build and Release apk
on: 
  push:

jobs:

  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'
    - run: cd ./dev/neat/ && flutter pub get
    - run: cd ./dev/neat/ && flutter build apk --release
    - run: ls
    - name: Create a Release APK
      uses: actions/upload-artifact@v2
      with:
        name: neat-app
        path: dev/neat/build/app/outputs/flutter-apk/app-release.apk